### ISSUE TITLE
rnadeg analysis using voom

### ISSUE THREAD

**Issue by Rahel14350** [pcheng84/TCGAbrowser#15]
Dear @pcheng84 ,
I have some question regarding rnadeg function that uses voom to produce differentially expressed genes between the high gene and low gene expression groups. 
- Are the low gene expression groups the base group for comparison (high VS low exp. groups; that says down-regulated genes are down in high group and up in low exp. group)?
- Is it possible to increase the number of genes in heatmap from top 100 DEGs to more or I have to do it separately in ComplexHeatmap if I want to see top 200 DEGs?
- The last question is that is it possible to include for example two gene of interest to the package workflow for example (SOX10+NRAS) or for this also I should extract the low and high groups separately and make a new pat file myself?

Many thanks in advance, if you could help me in any of those questions!
Kind Regards,
Rahel

**Comment by pcheng84** [comment]
Hi Rahel,

I fixed the rnaheat function, you can specifiy with "n = " how many genes you want to plot. The default now will plot all significant genes.

I do already have some functions prepared for two gene analysis, I will update the package with them this week.
Cheers,
Phil

**Comment by Rahel14350** [comment]
Dear Phil,

Many many thanks for your reply. Yes, this package is very helpful to check the differences between TCGA patients based on expression of specific genes. Would you please update me when it was possible to run it with two interested genes.
Regarding the first question, is it correct that the low expression group is the base level for Limma DEG analysis?

Kind Regards,
Rahel

**Comment by Rahel14350** [comment]
Dear Phil,

Thank you so very much. It will be so helpful for our group.
Just as a question, do you have any plan to extend this package for other
level of data in future?

Kind Regards,
Raheleh

**Comment by Rahel14350** [comment]
Dear Phil,
Would you please let me know if there is a new version of this package available?

Kind Regards,
Raheleh
