### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by jogiles** [pcheng84/TCGAbrowser#2]
I received the follow error. Any help would be greatly appreciated!

Error: package or namespace load failed for ‘TCGAbrowser’ in namespaceExport(ns, exports):
 undefined exports: genecoxsurv, rnamethdeg
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/TCGAbrowser’
Installation failed: Command failed (1)

**Comment by pcheng84** [comment]
Dear Jogiles,

I fix the exports it should work now. Could you pull from github and try?

Thanks,
Phil
